# Config

title: Aggregator GUI
description: 
baseUri: ws://localhost
port: 3000
wsport: 3001

api: 
  users: $ref api/users.yaml
  agg: $ref api/agg.yaml
  software: $ref api/software.yaml
  generator: $ref api/generator.yaml

# This section will be removed from client-side config
server:
  connectionString: postgres://localhost/sgapp
  expireToken: 600000
  
errors:
  SERVER_ERROR:
    code: -32001
    message: Ошибка на сервере
  FORBIDDEN:
    code: -32011
    message: Недостаточно прав
  UNAUTORIZED:
    code: -32012
    message: Пользователь неавторизован
  LOGIN_FAILED:
    code: -32021
    message: Неправильный логин/пароль
  DUPLICATE_USER:
    code: -32022
    message: Пользователь с таким именем уже существует


routes:
  /: 
    template: modules/agg/agg.html
    title: Агрегаторы
    controller: aggCtrl
    class: -nopaddings
    access: superadmin aggregator.admin aggregator.user  
  /software/: 
    template: modules/software/software.html
    title: Версии ПО агрегатора
    controller: softwareCtrl
    access: superadmin aggregator.user
  /generator/: 
    template: modules/generator/generator.html
    title: Генератор трафика
    controller: generatorCtrl
    class: -nopaddings
  /users/: 
    template: modules/users/users.html
    title: Пользователи
    controller: usersCtrl
    access: superadmin
  /dev/: 
    template: modules/dev/dev.html
    title: DEV
    hidden: true
    controller: devCtrl
  
