description: Aggregators

roles:
  read:
    superadmin
    aggregators.admin    
    aggregators.user
  write:
    superadmin
    aggregators.admin

model:
  id:
    type: number
    minLength: 1   
  date: date
  sn: string
  description: string
  license: array

license:
  id:
    type: number
    minLength: 1  
  ports:
    type: number
    minimum: 1
    maximum: 64    
  mpls: boolean
  mirror: boolean

methods:
  get:
    access: $ref roles/read

  add:
    params: 
      sn:
        type: string
        minLength: 1      
      description: string
    access: $ref roles/write

  update:
    params: $ref model
    required:
      - id
    access: $ref roles/write

  remove:
    params:
      id:
        type: number
        minLength: 1  
    required:
      - id
    access: $ref roles/write

  licenseadd:
    params: $ref license
    required:
      - id    
    access: $ref roles/write
