description: Aggregators

roles:
  read:
    superadmin
    aggregators.admin    
    aggregators.user
  write:
    superadmin
    aggregators.admin

model:
  id: string
  date: date
  sn: string
  description: string
  license: array

license:
  id: string
  ports: number
  mpls: boolean
  mirror: boolean

methods:
  get:
    access: $ref roles/read

  add:
    params: $ref model
    access: $ref roles/write

  update:
    params: $ref model
    access: $ref roles/write

  remove:
    params:
      id: string
    access: $ref roles/write

  licenseadd:
    params: $ref license
    access: $ref roles/write
