description: Aggregators

roles:
  read:
    superdmin
    aggregators.admin    
    aggregators.user
  write:
    superdmin
    aggregators.admin

model:
  id: string
  _date: date
  sn: string
  description: string
  license: array

license:
  id: string
  _date: date
  ports: number
  mpls: boolean
  mirror: boolean
  filename: string

methods:
  get:
    access: $ref roles/read

  add:
    params: $ref model
    access: $ref roles/write

  update:
    params: $ref model
    access: $ref roles/write

  remove:
    params:
      _id: string
    access: $ref roles/write

  licenseadd:
    params: $ref license
    access: $ref roles/write

  licenseremove:
    params: 
      index: string
    access: $ref roles/write

