description: User password authetification

methods:
  login:
    params:
      username: string
      password: string
    response:
      token: string
    
  logout:
    params:
      token: string