description: Generators

filemodel:
  date: date
  name: string
  username: string
  size: integer

genmodel:
  id:
    type: number
    minLength: 1
  name: string
  state: string
  files: array
  out: integer
  bitrate: integer
  loop: boolean
  swarm: boolean

methods:
  get:
    response: $ref genmodel

  add:
    params:
      name: string

  update:
    params: $ref genmodel

  remove:
    params:
      id:
        type: number
        minLength: 1

  getFiles:
    response: $ref filemodel

  removeFile:
    params:
      id:
        type: number
        minLength: 1
