description: Basic users model

roles:
  user: Пользователь
  superadmin: Администратор
  
  # Роли специфичные для агрегатора
  aggregator.user: Доступ к агрегаторам
  aggregator.admin: Администратор агрегаторов

model:
  id: string
  date: date
  name: string
  password: string
  state: boolean
  role: string

defaults:
  name: admin
  password: 0000
  state: true
  role: superadmin
    
methods:
  get:
    response:
      id: string
      date: date
      name: string
      state: boolean
      role: string

    access: superadmin

  login:
    params:
      name: string
      password: string
    response:
      token: string
      user: $ref model
    
  logout:
    params:
      token: string

  update:
    params: $ref model
    access: superadmin

  changePassword:
    params:
      id: string
      password: string

  remove:
    params:
      id: string
    access: superadmin

  switchState:
    params:
      id: string
      state: boolean
    access: superadmin

  register:
    params: 
      name: string
      password: string


